import type { Metadata } from "next";
import QueryCliProvider from "@/contexts/query-client-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Workout | Next.JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <QueryCliProvider>
          <div className="flex flex-col container mx-auto px-2">
            {children}
          </div>
        </QueryCliProvider>
      </body>
    </html>
  );
}
