import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Workout | Next.JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="flex flex-col container mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
